# Reshaping array using reshape method

In [1]:
# Reshaping 3x4 array to 2x2x3 array
import numpy as np
arr = np.array([1,2,3,4,5,6])

newarr = arr.reshape(2,3)
print("Original array:\n", arr)
print("-------------")
print("Reshaped array:\n", newarr)

Original array:
 [1 2 3 4 5 6]
-------------
Reshaped array:
 [[1 2 3]
 [4 5 6]]


# Flatten Array
- Flatten method flattens array to one dimension and returns copy of collapsed array.

In [ ]:
# Flatten array
arr = np.array([[4, 2, 3], [4, 5, 61]])
flat_arr = arr.flatten()
print ("Original array:\n", arr)
print ("Fattened array:\n", flat_arr)

Original array:
 [[ 4  2  3]
 [ 4  5 61]]
Fattened array:
 [ 4  2  3  4  5 61]


# NumPy Array Indexing and Slicing
## Basic Indexing

### Indexing allows usto access the individual elements or subsets of data.

In [ ]:
# 1D Array Indexing
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr[0]) #first element
print(arr[-1]) #last element
print(arr[3]) #fourth element

#2D array
num_2d_array = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
print("print dimension of array")
print(num_2d_array.ndim) # print dimension of array
print("print shape of the array")
print(num_2d_array.shape) #print shape of the array
print("print total number of items")
print(num_2d_array.size) # print total number of items

print("first row first element")
print(num_2d_array[0,0]) #first row first element = >1
print("last row last element")
print(num_2d_array[-1,-1]) #last row last element = >8
print("second row third element")
print(num_2d_array[1,2]) #second row third element = >6
print("third row second element")
print(num_2d_array[2,1])


(6,)
1
6
4
print dimension of array
2
print shape of the array
(3, 3)
print total number of items
9
first row first element
1
last row last element
8
second row third element
6
third row second element
7


# Slicing in NumPy
### In NumPy we can access the portion of an array using the slice operator ```:```
# 1-D Array Slicing
### Syntax: ```array[start:stop:step]```
- ```start```: Index of the first element to be included in slide
- ```stop```: index of the last element (exclusive)
- ```step```: step size between each element in the slice


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,10,11])

#slice array from index 2-6 (6-exclusive)
print(arr[2:6]) # [3,4,5,6] 

# slice array from 0 to 8 with a step size of 2
print(arr[0:8:2]) # [1,3,5,7]

# slice array from index 4 to last element
print(arr[4:])

# slice array from start to 5th index (5th index excluded)
print(arr[:5]) 

# negative index
print(arr[-1::-2]) # slice every second element form end to start

# we can also modify the array with slicing

arr[:5] = 100 # replace items from 0-5 with 100
print(arr)

[3 4 5 6]
[1 3 5 7]
[ 5  6  7  8 10 11]
[1 2 3 4 5]
[11  8  6  4  2]
[100 100 100 100 100   6   7   8  10  11]


# 2-D Array Slicing
Syntax: ```array[row_start:row_stop:row_step, col_start:col_stop:col_step]```

In [15]:
array_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array_2d.ndim)

# slice first row
print(array_2d[0:1])

# slice array from  first two rows and first two columns

print(array_2d[0:2,0:2])

2
[[1 2 3]]
[[1 2]
 [4 5]]


# Boolean Array Indexing
Boolean array indexing allows us to select elements from an array based on conditions. This technique is helpful when we need to filter elements based on certain condition.

In [16]:
# Creating an array
arr = np.array([5,10,15,20,25,30])

#Select elements greater than 15
print(arr[arr > 15])  # Output: [20 25 30]

# Select elements that are even
print(arr[arr % 2 == 0])  # Output: [10 20 30]

# Modifying elements that satisfy a condition
arr[arr > 15] = 99
print(arr)  # Output: [ 5 10 15 99 99 99]

#Boolean indexing on a 2-dimensiopnal array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract elements greater than 4
print(arr2d[arr2d > 4])

# Setting elements greater than 4 to zero
arr2d[arr2d > 4] = 0
print(arr2d)

[20 25 30]
[10 20 30]
[ 5 10 15 99 99 99]
[5 6 7 8 9]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


# NumPy Operation
- NumPy Arithmetic Array Operations
- NumPy Array Functions
- NumPy Comparison/Logical Operations
- NumPy Math Fuctions
- NumPy Constants
- NumPy Statistical Functions


# NumPy Arithmetic Operations
- add()
- subtract()
- multiply()
- divide()
- power()
- mod()

In [27]:
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

#add
addition = first_array + second_array
print(addition) 

#subtract
subtraction = first_array - second_array
print(subtraction)

#multiply
multiply = first_array * second_array
print(multiply)

#divide
divide = np.divide(first_array, second_array)
print(divide)

#power
power = np.power(first_array, 3)
print(power)

#mod
mod = np.mod(first_array, second_array)
print(mod)

[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[  1  27 125 343]
[1 3 5 7]


# NumPy Broadcasting
- Broadcasting in NumPy alllows it to perform arithmetic operations on arrays with different shapes.

In [28]:
arr1 = np.array([1,2,3,4])
arr2 = np.array(4)
result = arr1 * arr2
print(result)

[ 4  8 12 16]


# NumPy Array Functions
NumPy has various built-in functions for various purposes
-  Array Creation Functions: ```np.array(), np.zeros(), np.ones(), np.empty()``` etc
- Manipulation Functions: ```np.reshape(), np.transpose()```
- Mathematical Functions: ```np.add(), np.subtract(), np.sqrt(), np.power()```
- Statistical Functions: ```np.median(), np.mean(), np.std(), np.var()```

In [36]:
data = np.array([1,3,4,57,4,3])

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

std = np.std(data)
print(std)

var = np.var(data)
print(var)


12.0
3.5
20.149441679609886
406.0


# Array Manipulation Function

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9])

# reshape the 1D array into a 3D array
reshaped_array = np.reshape(numbers, (3, 3)) # 3 x 3 = 9
print(reshaped_array)  

# transpose the 3D array
transposed_array = np.transpose(reshaped_array)
print(transposed_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# NumPy Matrix Operations
- Matrix Multiplication ```np.matmul()```
- Dot Product ```np.dot()```
- Cross Product ```np.cross()```
- Transpose ```np.transpose```
- Inverse ```np.linalg.inverse()```
- Determinant ```linalg.det() linalg=>Linear Algebra```
- Norm ```np.linalg.norm()```
- Trace ```np.linalg.trace()```

In [42]:
matrix_one = [
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ]
matrix_two = [
                [4,5],
                [6,7],
                [9,2]
            ]

multiply = np.matmul(matrix_one, matrix_two)
print(multiply)

[[ 43  25]
 [100  67]
 [157 109]]
